ecommerce/cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
	re_path(r'^$',views.cart_detail,name='cart_detail'),
	re_path(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
	re_path(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.static import serve

from ecommerce import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('',include('mainsite.urls')),
    path('user/',include('accounts.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/',include('payment.urls')),
    path('ticket',include('chat.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models

# Create your models here.

ecommerce/cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

ecommerce/cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.decorators.http import require_POST
from mainsite.models import addProduct
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request,product_id):

	cart = Cart(request)
	product = get_object_or_404(addProduct,id=product_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product,quantity=cd['quantity'],update_quantity=cd['update'])
	return redirect('cart:cart_detail')

def cart_remove(request,product_id):
	cart = Cart(request)
	product = get_object_or_404(addProduct,id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')

def cart_detail(request):
	r = request.user
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
	context = {
		'cart': cart,
		'r': r
	}
	return render(request, 'cart/detail.html', context)

ecommerce/cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
	Your Shopping Cart
{% endblock %}
{% block content %}
	
	<table>

		<thead class='t-head'>
			<h1>Your Shopping Cart</h1>
			<tr>
				<th>Image</th>
				<th>Product</th>
				<th>Quantity</th>
				<th>Remove</th>
				<th>Unit Price</th>
				<th>Price</th>
			</tr>
		</thead>
		<tbody>
			{% if cart %}
				{% for item in cart %}
					{% with  product=item.product %}
					    <tr>
					    	<td>
					    		<a href="{{product.get_absolute_url}}">
					    			<img src="
					    				{% if product.img %}
					    					{{product.img.url}}
					    				{% else %}
					    					{% static 'img/default.png' %}
					    				{% endif %}"
					    			width="100px">
					    		</a>
					    	</td>
					    	<td>{{product.Title}}</td>
					    	<td>
					    		<form method="post" action="{% url 'cart:cart_add' product.id %}">
					    			{% csrf_token %}
					    			{{item.update_quantity_form.quantity}}
					    			{{item.update_quantity_form.update}}
					    			<input type="submit" value="Update">
					    		</form>
					    	</td>
					    	<td>
					    		<a href="{% url 'cart:cart_remove' product.id%}">
					    			Remove
					    		</a>
					    	</td>
					    	<td>
					    		{{item.price}}
					    	</td>
					    	<td>
					    		{{item.total_price}}
					    	</td>
					    </tr>

					{% endwith %}
				{% endfor %}
			{% else %}
				<tr >
					<td colspan="4" style="width:100%;text-align:center;">there is no product !</td>
				</tr>
			{% endif %}
				<tr class="total">
					<td>
						Total
					</td>
					<td colspan="4"></td>
					<td class="num">${{cart.get_total_price}}</td>
				</tr>
		</tbody>
	</table>
	<p class="text-right">
		<a href="/">Continu shopping</a>
		<a href="/orders/create/">Checkout</a>
	</p>
{% endblock %}