ecommerce/cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
	re_path(r'^$',views.cart_detail,name='cart_detail'),
	re_path(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
	re_path(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.static import serve

from ecommerce import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('',include('mainsite.urls')),
    path('user/',include('accounts.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/',include('payment.urls')),
    path('ticket',include('chat.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/mainsite/urls.py
from django.urls import path

from mainsite import views


urlpatterns = [
    path('',views.home),
    path('all',views.all),
    path('search/',views.search),
    path('product/<int:id>-<str:slug>/',views.oneProduct),
    path('sales/',views.salesPage),
    path('contact/',views.contact)
]

ecommerce/mainsite/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class addProduct(models.Model):
    cat_list=(('Dresses','Dresses'),('Blouses','Blouses'),('T-shirts','T-shirts'),('OutWare','OutWare'),('Bags','Bags'),('Other','Other'))
    Title = models.CharField(max_length=200)
    Category = models.CharField(choices=cat_list,max_length=50,default='Other')
    Price = models.IntegerField()
    Discount_Price = models.IntegerField(blank=True,null=True)
    Details = models.TextField()
    Information = models.TextField()
    img = models.ImageField(upload_to='media',default='media/default.BMP')

ecommerce/mainsite/views.py
from django.http import HttpResponse
from django.shortcuts import render
from cart.forms import CartAddProductForm
# Create your views here.
from mainsite.models import addProduct
from orders.models import OrderItem


def home(request):
    r = request.user
    x = OrderItem.objects.all()
    f_arr = []
    s_arr = []
    prod_ids = []
    final_list = []
    for i in x:
        f_arr.append(i)

    for i in f_arr:
        s_arr.append(i.product.id)

    for i in range(0,8):
        try:
            m = max(set(s_arr), key=s_arr.count)
            prod_ids.append(m)
            s_arr = [x for x in s_arr if x != m]
        except:
            prod_ids.append(i)
    for i in prod_ids:
        pop_products = addProduct.objects.get(id=i)
        final_list.append(pop_products)

    context = {
        'r':r,
        'final_list':final_list
    }
    return render(request,'index.html',context)

def all(request):
    products = addProduct.objects.all()
    r = request.user
    context = {
        'products': products,
        'r':r
    }
    return render(request,'all.html',context)

def search(request):
    sproducts = addProduct.objects.filter(Category = request.POST.get('re'))
    r = request.user
    p = request.POST.get('re')
    context = {
        'sproducts':sproducts,
        'r':r,
        'p':p
    }
    return render(request,'search.html',context)

def oneProduct(request,id,slug):
    oneP = addProduct.objects.get(id=id,Title=slug)
    alsoLike = addProduct.objects.filter(Category = oneP.Category).exclude(id=id)
    cart_product_form = CartAddProductForm()
    r = request.user
    context = {
        'oneP':oneP,
        'alsoLike':alsoLike,
        'r':r,
        'cart_product_form':cart_product_form
    }
    return render(request,'product.html',context)

def salesPage(request):
    products = addProduct.objects.filter(Discount_Price__isnull= False)
    print(products)
    context = {
        'products':products

    }
    return render(request,'sales.html',context)
def contact(request):
    return render(request,'contact.html')

ecommerce/mainsite/templates/all.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block title %} Amr Shop - All Products {% endblock %}
{% block content %}
{% load static  %}

        <section class="search-all" style="margin-bottom:30px">
            <div class="header-all text-center">
                <div class="row">
                    <div class="col-lg-12">
                        <h1>All Products</h1>
                    </div>


                <!-- Search -->

                    <div class="container text-center">
                        <div class="row">


                            <form action="/search/" method="post" class="col-lg-2 col-md-2 col-xs-6">
                                {% csrf_token %}
                                <input type="hidden" name="re" value="Dresses" readonly>

                                <button style="width:100%;font-size:20px" class="btn btn-danger" type="submit">Dresses</button>
                            </form>
                            <form action="/search/" method="post" class="col-lg-2 col-md-2 col-xs-6">
                                {% csrf_token %}

                                <input type="hidden" name="re" value="OutWare" readonly>

                                <button style="width:100%;font-size:20px" class="btn btn-primary" type="submit">OutWare</button>
                            </form>
                            <form action="/search/" method="post" class="col-lg-2 col-md-2 col-xs-6">
                                {% csrf_token %}

                                <input type="hidden" name="re" value="Blouses" readonly>

                                <button style="width:100%;font-size:20px" class="btn btn-danger" type="submit">Blouses</button>
                            </form>
                            <form action="/search/" method="post" class="col-lg-2 col-md-2 col-xs-6">
                                {% csrf_token %}

                                <input type="hidden" name="re" value="T-shirts" readonly>

                                <button style="width:100%;font-size:20px" class="btn btn-primary" type="submit">T-shirts</button>
                            </form>
                            <form action="/search/" method="post" class="col-lg-2 col-md-2 col-xs-6">
                                {% csrf_token %}

                                <input type="hidden" name="re" value="Other" readonly>
                                <button style="width:100%;font-size:20px" class="btn btn-danger" type="submit">Other</button>
                            </form>
                            <form action="/search/" method="post" class="col-lg-2 col-md-2 col-xs-6">
                                {% csrf_token %}

                                <input type="hidden" name="re" value="Bags" readonly>
                                <button style="width:100%;font-size:20px" class="btn btn-primary" type="submit">Bags</button>
                            </form>
                        </div>
                    </div>





        </section>
        <section class="all-products">
            <div class="products visible-lg visible-md visible-sm text-center">
                <div class="row">
                    {% for products in products %}
                    <div class="col-lg-3 col-md-3 col-sm-6">
                        <a href="/product/{{products.id}}-{{products.Title}}"><div class="product-box">
                            <img class="img-responsive" src="{{products.img.url}}"/>
                            <div id="sale">
                                <button type="button" class="btn btn-danger prod-btn">{{products.Discount_Price|mul:100|div:products.Price|floatformat }} %</button>
                            </div>
                            <div id="new">
                                <button type="button" class="btn prod-btn">{{products.Discount_Price|mul:100|div:products.Price|floatformat }} %</button>
                            </div>
                            <p>{{products.Title}}</p>
                            {% if products.Discount_Price %}
                            <p id="price">{{products.Discount_Price}} <strike>{{products.Price}} </strike></p>

                            {% else %}
                            <p id="price">{{products.Price}} </p>
                            {% endif %}
                            </div>
                        </a>
                    </div>
                    {% endfor %}


                </div>
            </div>

            <!-- Products for mobile -->
            <div class="mob-products visible-xs">
                <div class="container">
                        {% for products in products %}
                        <div class="product-box">
                            <div class="row">

                                <div class="col-sm-6 col-xs-12">
                                        <a href="/product/{{products.id}}-{{products.Title}}"><img class="img-responsive" src="{{products.img.url}}"/></a>
                                </div>
                            </div>
                            <div class="row text-center">
                                <div class="col-sm-6 col-xs-12">
                                        <p>{{products.Title}}</p>
                                    {% if products.Discount_Price %}
                            <p id="price">{{products.Discount_Price}} <strike>{{products.Price}} </strike></p>

                            {% else %}
                            <p id="price">{{products.Price}} </p>
                            {% endif %}

                                    <button onclick="window.location.href='/product/{{products.id}}-{{products.Title}}'"  type="button" class="btn btn-primary btn-btnbtn">Read More</button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6 col-xs-12">
                                    <div class="mob-lineline"></div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}


                </div>
            </div>
        </section>

        {% endblock %}

ecommerce/mainsite/templates/base.html
{% load static  %}
{% load mathfilters %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="stylesheet" href="{% static  'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static  'css/style.css' %}">
        <link rel="stylesheet" href="{% static  'css/all.min.css'%} ">
        <link rel="stylesheet" href="{% static  'css/animate.css' %}">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
       <script src="{% static  'js/jquery-3.4.0.min.js' %}"></script>
       <script type="text/javascript" src="{% static  'js/bootstrap.min.js' %}"></script>
        <script src="{% static  'js/all.min.js' %}"></script>
        <script src="{% static 'js/my.js' %}"></script>
         <script src="{% static  'js/wow.min.js' %}"></script>
        <script>
              new WOW().init();
              </script>

    <section class="navb">
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Amr Shop</a>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home <span class="sr-only">(current)</span></a></li>
                <li><a href="/sales">Sales</a></li>
                <li><a href="/all">All Products</a></li>
                <li><a href="/contact">Contact Us</a></li>


              </ul>

              <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                  <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="/user/profile/dashboard">My Dashboard</a></li>
                    <li><a href="/user/view/{{r}}">My Profile</a></li>

                    <li role="separator" class="divider"></li>
                      {% if user.is_superuser %}
                    <li><a href="/ticket/all-tickets">View all Users Tickets</a></li>
                      {% else %}
                      <li><a href="/ticket/">Support Ticket</a></li>
                      {% endif %}
                      <li><a href="/user/logout/"><button class="btn btn-danger">Logout</button></a></li>
                  </ul>
                </li>
                  {% else %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="/user/login/">Login</a></li>
                    <li><a href="/user/signup/">Register</a></li>



                  </ul>
                </li>
                    {% endif %}

                  <!-- END -->
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="card-img fas fa-shopping-bag"></i></a>
                  <ul class="dropdown-menu">
                      {% for item in cart %}
					{% with  product=item.product %}
                    <li>
                        <div class="row">
                            <div class="cart-img">
                                <div class="col-lg-6">
                                    <img class="img-responsive cart-img-size" src="{{product.img.url}}"/>
                                </div>
                                <div class="col-lg-6 text-center">
                                    <p class="cart-price-size">Total Price: {{item.total_price}}$</p>
                                </div>
                                <div class="col-lg-6 text-center">
                                    <p class="cart-price-size">Total Quantity: {{item.quantity}}</p>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li role="separator" class="divider"></li>


                      {% endwith %}
                      {% endfor %}
                      <div class="cart-final text-center">
                        <li>{{cart.get_total_price}}$ <button onclick="window.location.href='{% url 'cart:cart_detail' %}'" class="btn btn-danger">View Cart</button></li>
                    </div>
                  </ul>
                </li>

                  <!-- END -->



              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
    </section>

       {% block content %}



        {% endblock %}
        <section class="first-footer wow flipInX">
            <div class="container">
                <div class="col-lg-5 col-md-5  col-sm-6">
                    <h3>Amr Shop</h3>
                    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>
                    <div class="social-media">
                        <a href="http://google.com"><i class="fab fa-facebook-square icon" ></i></a>
                        <a href="http://google.com"><i class="fab fa-google icon" ></i></a>
                        <a href="http://google.com"><i class="fab fa-github-square icon"></i></a>
                        <a href="http://google.com"><i class="fab fa-twitter-square icon" ></i></a>
                    </div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-6">
                        <h3>Products</h3>
                        <ul class="list-unstyled">
                            <a href=""><li>Price drop</li></a>
                            <a href=""><li>New products</li></a>
                            <a href=""><li>Best sales</li></a>
                        </ul>
                    </div>
                <div class="clearfix visible-sm visible-xs"></div>
                    <div class="col-lg-2 col-md-2 col-sm-6">
                        <h3>Information</h3>
                        <ul class="list-unstyled">
                            <a href=""><li>Delivery</li></a>
                            <a href=""><li>Legal Notice</li></a>
                            <a href=""><li>Terms</li></a>
                            <a href=""><li>About Us</li></a>
                            <a href=""><li>Payment</li></a>
                            <a href=""><li>Conact Us</li></a>
                            <a href=""><li>sitemap</li></a>
                            <a href=""><li>store</li></a>
                        </ul>
                    </div>
                    <div class="col-lg-2 col-md-2">
                        <h3>Your Account</h3>
                        <ul class="list-unstyled">
                            <a href=""><li>Address</li></a>
                            <a href=""><li>Credit Card</li></a>
                            <a href=""><li>Orders</li></a>
                            <a href=""><li>Personal Info.</li></a>
                        </ul>
                    </div>
            </div>
        </section>
        <section class="footer">
            <div class="container">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    © 2019 - <a href='https://www.facebook.com/amr.elsayed.73999'> Amr Elsayed</a>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <img class="img-responsive" src="{% static 'img/payments.jpg' %}"/>
                </div>
            </div>
        </section>
    </body>
</html>

ecommerce/mainsite/templates/checkout.html
{% extends 'base.html' %}
{% block title %} Amr Shop - All Products {% endblock %}
{% block content %}
{% load static  %}
        <section class="check-out">
            <div class="container">
                <h1 class="text-center">CheckOut</h1>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-8">
                                <!-- product -->
                                <div class="row text-center">
                                    <div class="col-lg-2">
                                        <h3 class="text-center">Item #1</h3>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="product-checkout">
                                            <img class="img-responsive" src="{% static 'img/1.jpg' %}"/>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <p class="price-checkout">250$</p>
                                    </div>
                                </div>
                                <!-- end product -->
                                <li role="separator" class="divider"></li>
                                 <!-- product -->
                                <div class="row text-center">
                                    <div class="col-lg-2">
                                        <h3 class="text-center">Item #2</h3>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="product-checkout">
                                            <img class="img-responsive" src="{% static 'img/2.jpg' %}"/>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <p class="price-checkout">250$</p>
                                    </div>
                                </div>
                                <!-- end product -->
                            </div>
                            
                            <div class="checkout-box text-center">
                                <div class="col-lg-4">
                                
                                    <div class="row">
                                        <p class="price-box-rr">500$</p>
                                    </div>
                                    <div class="row">
                                       <button class="btn btn-primary">CheckOut with Paypal</button>
                                    </div>
                                    
                                </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </section>
        

{% endblock %}

ecommerce/mainsite/templates/contact.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block title %} Amr Shop - All Products {% endblock %}
{% block content %}
{% load static  %}

        <section class="search-all" style="margin-bottom:30px">
            <div class="container">
                <div class="row text-center">
                    <div class="col-xs-16">
                        <h1>This website designed and developed By : <a href="https://www.facebook.com/amr.elsayed.73999">Amr Elsayed</a>
                        </h1>
                        <h1>E-mail : newsifb@gmail.com</h1>
                        <h1>Tel : +2 011 211 479 61</h1>
                    </div>
                </div>
            </div>


        </section>

        {% endblock %}

ecommerce/mainsite/templates/product.html
{% extends 'base.html' %}
{% block title %} Amr Shop - All Products {% endblock %}
{% block content %}
{% load static  %}
        <section class="one-product">
            <div class="row">
                <div class="col-lg-5">
                    <img class="img-responnsive" src="{{oneP.img.url}}" style="width: 70%"> </div>
                <div class="col-lg-7">
                    <h1>{{oneP.Title}}</h1>
                    {% if oneP.Discount_Price %}
                            <h1><p id="price">{{oneP.Discount_Price}} <strike>{{oneP.Price}} </strike></p></h1>

                            {% else %}
                           <h1> <p id="price">{{oneP.Price}} </p></h1>
                            {% endif %}
                    <p>{{oneP.Information}}</p>
                        <div class="social-media">
                        <a href="http://google.com"><i class="fab fa-facebook-square icon" ></i></a>
                        <a href="http://google.com"><i class="fab fa-google icon" ></i></a>
                        <a href="http://google.com"><i class="fab fa-github-square icon"></i></a>
                        <a href="http://google.com"><i class="fab fa-twitter-square icon" ></i></a>
                    </div>


                        <div class="row" style="margin-top: 50px;">

                                <form method="post" action="{% url 'cart:cart_add' oneP.id %}">
                                {% csrf_token %}
                                {{cart_product_form}}
                                <input class="btn btn-primary" type="submit" value="Add to Cart">

                            </form>


                        </div>
                        <div class="row">
                            <!--<a href=""><button type="button" class="btn btn-danger text">ADD TO CART</button></a>-->

                        </div>
                        <div class="row  text-center" style="width: 70%">
                    <div class="col-lg-4 col-md-4 col-xs-4">
                        <img src="{% static 'img/discount.jpg'%}" width="50" height="53"/>
                        <h6>Discount System</h6>
                    </div>
                    <div class="col-lg-4 col-md-4 col-xs-4">
                        <img src="{% static 'img/free-del.jpg' %}" width="50" height="53"/>
                        <h6>Free Delivery</h6>
                    </div>
                    <div class="col-lg-4 col-md-4 col-xs-4">
                        <img src="{% static 'img/support247.jpg' %}" width="50" height="53"/>
                        <h6>Support 24/7</h6>
                    </div>
                </div>

                
            </div>    
                </div>
            <div class="row">
                <div class="col-lg-12">
                    <h3>Information</h3>
                    <div class="infotag"></div>
                </div>
                <div class="col-lg-12">
                    <p>{{oneP.Details}}</p>
                </div>
            </div>
        </section>
        
        <section class="alsolike">
            <div class="row text-center">
                <div class="col-lg-12">
                    <h1>You Might Also Like</h1>
                </div>

                <div class="products visible-lg visible-md visible-sm text-center">

                <div class="row">
                    {% for alsoLike in alsoLike %}
                    <div class="col-lg-3 col-md-3 col-sm-6">
                        <a href="/product/{{alsoLike.id}}-{{alsoLike.Title}}"><div class="product-box">
                            <img class="img-responsive" src="{{alsoLike.img.url}}"/>
                            <div id="sale">
                                <button type="button" class="btn btn-danger prod-btn">-20%</button>
                            </div>
                            <div id="new">
                                <button type="button" class="btn prod-btn">-20%</button>
                            </div>
                            <p>{{alsoLike.Title}}</p>
                            {% if alsoLike.Discount_Price %}
                            <p id="price">{{alsoLike.Discount_Price}} <strike>{{alsoLike.Price}} </strike></p>

                            {% else %}
                            <p id="price">{{alsoLike.Price}} </p>
                            {% endif %}
                            </div></a>
                    </div>
                    {% endfor %}
                    </div>
                    
                </div>
                
                
                
            </div>
            <!-- Products for mobile -->
            <div class="mob-products visible-xs">
                <div class="container">
                        {% for alsoLike in alsoLike %}
                        <div class="product-box">
                            <div class="row">

                                <div class="col-sm-6 col-xs-12">
                                        <a href="/product/{{alsoLike.id}}-{{alsoLike.Title}}"><img class="img-responsive" src="{{alsoLike.img.url}}"/></a>
                                </div>
                            </div>
                            <div class="row text-center">
                                <div class="col-sm-6 col-xs-12">
                                        <p>{{alsoLike.Title}}</p>
                                    {% if alsoLike.Discount_Price %}
                            <p id="price">{{alsoLike.Discount_Price}} <strike>{{alsoLike.Price}} </strike></p>

                            {% else %}
                            <p id="price">{{alsoLike.Price}} </p>
                            {% endif %}

                                    <button onclick="window.location.href='/product/{{alsoLike.id}}-{{alsoLike.Title}}'"  type="button" class="btn btn-primary btn-btnbtn">Read More</button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6 col-xs-12">
                                    <div class="mob-lineline"></div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}


                </div>
            </div>
            </div>
        </section>
        {% endblock %}